# Site settings
title: cnly.github.io
baseurl: ""
url: "https://cnly.github.io"
github_username: Cnly
exclude: ['about.md']
description: > # this means to ignore newlines until "baseurl:"
  A tiny site of Cnly's.<br />
  Powered by Jekyll + GitHub Pages.
  
githubio_https_redirect: true
google_analytics: UA-54761187-1

paginate: 10 # pagination based on number of posts

# Build settings
markdown: kramdown


defaults:
  - scope:
      type: posts
    values:
      layout: post
      author: Cnly
      
gems:
  - jekyll-assets

assets:
  sources:
    - _includes/fpw/fpw_files
